### PR TITLE
Fix BeautifulSoup parent package

### PR DESCRIPTION
**Pull request by Samweli**
Fixes https://github.com/kartoza/sg-diagram-downloader/issues/59

The original error can also occur in Linux if `bs4` package is not installed in the system and/or QGIS can't find the `BeautifulSoup` module in the plugin third party libraries.

See
image

### CODE REVIEW

**Comment by NyakudyaA** [comment]
LGTM @Samweli Can we also add a plugin dependency in metadata.txt so that users can know that they need to install xyz packages as well

**Comment by Samweli** [comment]
> LGTM @Samweli Can we also add a plugin dependency in metadata.txt so that users can know that they need to install xyz packages as well

@NyakudyaA do you mean to include the third party libraries list in the metadata.txt?

**Comment by NyakudyaA** [comment]
> > LGTM @Samweli Can we also add a plugin dependency in metadata.txt so that users can know that they need to install xyz packages as well
> 
> @NyakudyaA do you mean to include the third party libraries list in the metadata.txt?

Yes, QGIS supports adding them as plugin_dependencies. i.e `plugin_dependencies=simplejson` etc

**Comment by Samweli** [comment]
> Yes, QGIS supports adding them as plugin_dependencies. i.e `plugin_dependencies=simplejson` etc

Right @NyakudyaA but that we can only use that to specify if there are other QGIS plugins that the plugin depends on and not for normal python packages such as `bs4`.

**Comment by NyakudyaA** [comment]
LGTM @Samweli Can we also add a plugin dependency in metadata.txt so that users can know that they need to install xyz packages as well

> > Yes, QGIS supports adding them as plugin_dependencies. i.e `plugin_dependencies=simplejson` etc
> 
> Right @NyakudyaA but that we can only use that to specify if there are other QGIS plugins that the plugin depends on and not for normal python packages such as `bs4`.

We can do that, but it will not install the packages for users. It will still require them to install the packages themselves. I will merge this now as I have tested on windows and mac and seems to work

**Pull request merged**
